# Generated by Django 4.2 on 2026-01-15 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='sent_to_telegram',
            new_name='admin_notified',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='level',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='telegram_chat_id',
        ),
        migrations.AddField(
            model_name='level',
            name='question_count',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='level',
            name='time_limit',
            field=models.IntegerField(default=15, help_text='Daqiqa bilan'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='telegram_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Soniyalar bilan'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.level')),
            ],
        ),
        migrations.AddField(
            model_name='testresult',
            name='session',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='test_app.testsession'),
            preserve_default=False,
        ),
    ]
